### PR TITLE
Backlogpage

### PR DESCRIPTION
**Pull request by cheresandreea**

### CODE REVIEW

**Review by Dumitrescu-Razvan — APPROVED** [review]
Technical Overview:

package.json:
The file had dependencies added for @radix-ui/react-label and @radix-ui/react-select. These changes align with the common practices of updating dependencies to include new UI components.

Jyros/src/components/TaskTable/TaskTable.css:
The CSS file changes include updates to the dimensions and padding of the search bar, adjustments to the positioning of the search icon, and additional styles for new UI elements like dropdown divs and user logos.

Jyros/src/components/TaskTable/TaskTable.tsx:
New imports have been added for icons, badges, and additional UI elements. The table now includes these UI elements to enhance the visual representation of tasks, including priority icons, status badges, and user logos.

Jyros/src/pages/BacklogPage.tsx:
The BacklogPage component now includes new imports and components for SideBar, SidebarProvider, TeamMates, and TicketCreate. These additions suggest enhancements to the sidebar functionality and team management features on the Backlog page.

These changes generally appear to be improvements and additions to the existing UI components and functionality. However, it is always a good idea to conduct thorough testing to ensure there are no unintended side effects. If you need specific feedback on any particular part, let me know!

**Comment by AlexandruCostea** [comment]
LGTM👍

**Comment by Dumitrescu-Razvan** [comment]
> LGTM👍

not detalied enough, i hope you will learn from this and correct yourself in the future

**Comment by cernescutudor** [comment]
LGTM :+1:

**Comment by AlexandruCostea** [comment]
> > LGTM👍
> 
> not detalied enough, i hope you will learn from this and correct yourself in the future

LBTM👎

**Pull request merged**
